// Generated by CoffeeScript 1.6.2
(function() {
  var WindowHandler, WindowProvider, log, test,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  yepnope({
    load: ['lib/zepto.min.js', 'css/tango3.css'],
    complete: function() {
      return $(document).ready(function() {
        return test();
      });
    }
  });

  log = function() {
    var arr, item, _i, _len;

    arr = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      item = arguments[_i];
      arr.push(item);
    }
    return console.log.apply(console, arr);
  };

  test = function() {
    var TestProvider, div, provider, win;

    TestProvider = (function(_super) {
      __extends(TestProvider, _super);

      function TestProvider() {
        var i, _i;

        this.lines = [];
        for (i = _i = 0; _i < 50; i = ++_i) {
          this.lines.push("Line\tno " + i);
        }
      }

      TestProvider.prototype.size = function() {
        return this.lines.length;
      };

      TestProvider.prototype.get = function(index) {
        return this.lines[index];
      };

      TestProvider.prototype.editable = function(index, column) {
        return true;
      };

      return TestProvider;

    })(WindowProvider);
    provider = new TestProvider();
    win = new WindowHandler();
    div = $(document.createElement('div')).attr('id', 'testWin');
    div.appendTo(document.body);
    div.append(win.init(provider));
    log('Win created');
    return setTimeout(function() {
      return win.refresh();
    }, 0);
  };

  WindowProvider = (function() {
    function WindowProvider() {}

    WindowProvider.prototype.size = function() {
      return 0;
    };

    WindowProvider.prototype.get = function(index) {
      return '';
    };

    WindowProvider.prototype.editable = function(index, column) {
      return false;
    };

    return WindowProvider;

  })();

  WindowHandler = (function() {
    function WindowHandler() {}

    WindowHandler.prototype.init = function(provider) {
      var div;

      this.provider = provider;
      this.from = 0;
      this.selected = -1;
      this.cursorRow = 0;
      div = $(document.createElement('div')).addClass('win root');
      this.lines = $(document.createElement('div')).addClass('win lines').appendTo(div);
      this.scroll = $(document.createElement('div')).addClass('win scroll').appendTo(div);
      this.char = $(document.createElement('div')).addClass('win char hidden').appendTo(div);
      this.char.text('0');
      this.lineDivs = [];
      return div;
    };

    WindowHandler.prototype.moveCursor = function(div, text, pos) {
      var range, selection;

      range = document.createRange();
      if (pos < text.length) {
        range.setStart(div.childNodes[0], pos);
        range.collapse(true);
      } else {
        range.selectNodeContents(div);
        range.collapse(false);
      }
      selection = window.getSelection();
      selection.removeAllRanges();
      return selection.addRange(range);
    };

    WindowHandler.prototype.editLine = function(index, position) {
      var div, text;

      if (position == null) {
        position = -1;
      }
      div = this.lineDivs[index];
      div.addClass('line_edit');
      div.focus();
      this.selected = this.from + index;
      if (this.provider.editable(this.selected, position)) {
        text = this.provider.get(this.selected);
        div.text(text);
        this.edit = true;
        div.attr('contentEditable', true);
        if (this.cursorRow >= 0) {
          return this.moveCursor(div.get(0), text, this.cursorRow);
        }
      }
    };

    WindowHandler.prototype.cursorPos = function(div) {
      var charCount, range, treeWalker;

      if (window.getSelection().rangeCount === 0) {
        return -1;
      }
      range = window.getSelection().getRangeAt(0);
      treeWalker = document.createTreeWalker(div.get(0), NodeFilter.SHOW_TEXT, function(node) {
        var nodeRange;

        nodeRange = document.createRange();
        nodeRange.selectNodeContents(node);
        if (nodeRange.compareBoundaryPoints(Range.END_TO_END, range) < 1) {
          return NodeFilter.FILTER_ACCEPT;
        } else {
          return NodeFilter.FILTER_REJECT;
        }
      }, false);
      charCount = 0;
      while (treeWalker.nextNode()) {
        charCount = charCount + treeWalker.currentNode.length;
      }
      if (range.startContainer.nodeType === 3) {
        charCount = charCount + range.startOffset;
      }
      return charCount;
    };

    WindowHandler.prototype.finishEdit = function(index, reason) {
      var div, pos, text;

      if (reason == null) {
        reason = 'none';
      }
      div = this.lineDivs[index];
      pos = this.cursorPos(div);
      log('finishEdit', pos, this.edit, index, reason);
      if (this.edit && pos >= 0) {
        this.cursorRow = pos;
      }
      div.removeClass('line_edit');
      if (this.edit) {
        text = div.text();
        div.text(text);
        div.attr('contentEditable', false);
      }
      return this.edit = false;
    };

    WindowHandler.prototype.renderLine = function(index, lineIndex) {
      var div, text;

      div = this.lineDivs[lineIndex];
      div.attr('class', 'win char line');
      if (index < this.provider.size()) {
        text = this.provider.get(index);
        return div.text(text);
      } else {
        return div.text('');
      }
    };

    WindowHandler.prototype.createLine = function(index) {
      var div,
        _this = this;

      div = $(document.createElement('div'));
      div.attr('tabindex', 0);
      this.lines.append(div);
      this.lineDivs.push(div);
      div.on('click', function() {
        var selIndex;

        selIndex = _this.selected - _this.from;
        if (selIndex !== index) {
          _this.finishEdit(selIndex, 'before click');
          _this.cursorRow = _this.cursorPos(div);
          return _this.editLine(index);
        }
      });
      return div.on('keydown', function(e) {
        if (e.keyCode === 13) {
          return false;
        }
        if (e.keyCode === 33) {
          _this.pg(index, true);
          return false;
        }
        if (e.keyCode === 34) {
          _this.pg(index, false);
          return false;
        }
        if (e.keyCode === 38) {
          return _this.cursor(index, 'up');
        }
        if (e.keyCode === 40) {
          return _this.cursor(index, 'down');
        }
        return log('Key', e.keyCode);
      });
    };

    WindowHandler.prototype.pgScrollSize = function() {
      var size;

      size = Math.round(this.rows * 0.5);
      if (size <= 0) {
        size = 1;
      }
      return size;
    };

    WindowHandler.prototype.cursor = function(index, dir) {
      if (dir === 'up') {
        if (this.selected > 0) {
          this.finishEdit(index, 'cursor up');
          this.selected = this.selected - 1;
        }
        this.display(true);
        return false;
      }
      if (dir === 'down') {
        if (this.selected < this.provider.size() - 1) {
          this.finishEdit(index, 'cursor down');
          this.selected = this.selected + 1;
        }
        this.display(true);
        return false;
      }
      return true;
    };

    WindowHandler.prototype.pg = function(index, up) {
      if (up == null) {
        up = false;
      }
      if (up) {
        this.from = this.from - this.pgScrollSize();
      } else {
        this.from = this.from + this.pgScrollSize();
      }
      this.finishEdit(index);
      return this.display();
    };

    WindowHandler.prototype.display = function(show_cursor) {
      var i, normFrom, size, _i, _ref, _results,
        _this = this;

      if (show_cursor == null) {
        show_cursor = false;
      }
      size = this.provider.size();
      normFrom = function() {
        if (_this.from + _this.rows > size) {
          _this.from = size - _this.rows;
        }
        if (_this.from < 0) {
          return _this.from = 0;
        }
      };
      normFrom();
      if (show_cursor) {
        if (this.selected < this.from || this.selected >= this.from + this.rows) {
          this.from = this.selected - Math.round(this.rows / 2);
          normFrom();
        }
      }
      _results = [];
      for (i = _i = 0, _ref = this.rows; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.renderLine(this.from + i, i);
        if (this.from + i === this.selected) {
          _results.push(this.editLine(i));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    WindowHandler.prototype.refresh = function() {
      var cols, i, rows, _i, _ref;

      this.rows = Math.floor(this.lines.height() / this.char.height());
      this.cols = Math.floor(this.lines.width() / this.char.width());
      if (rows === 0) {
        rows = 1;
      }
      if (cols === 0) {
        cols = 1;
      }
      this.lineDivs = [];
      for (i = _i = 0, _ref = this.rows; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.createLine(i);
      }
      this.display();
      if (this.selected === -1) {
        return this.editLine(0);
      }
    };

    return WindowHandler;

  })();

}).call(this);
